### ISSUE TITLE
Unclear license 

### ISSUE THREAD

**Issue by techxplorer** [dankogai/swift-json#10]
Hi,

In the root of the repo you have a LICENSE file that is the MIT license. At the top of your file you have a copyright statement that says "all rights reserved". 

If your intention is to distribute this code under the MIT license, could you please add the MIT license to the source code file itself? That would clarify the license that accompanies the code.

I've tried three different libraries for parsing JSON over the past few days and yours is the only one that works. I'd appreciate it if you could clarify this license issue so that I can continue to use your excellent library.

**Comment by LinusGeffarth** [comment]
I guess that's just the line Xcode adds to each new file on top.
