### ISSUE TITLE
Sort is changed after updating to newer version

### ISSUE THREAD

**Issue by petershaw** [dankogai/swift-json#22]
Hi, 
I just dated swift-json up and my tests are failing. I figured out that the sorting is different. 

This is my test String: 

```swift
    let s: String = "{\"debug\": \"on\", \"window\": {\"title\": \"Sample Widget\", \"width\": 500},\"image\": {\"name\": \"sun1\", \"hOffset\": 250 }}"
    let json = JSON(string: s)
```

Bevor the update the nodes are ['debug', 'window' and 'image'], after the update "debug" is at the end.

**Comment by dankogai** [comment]
JS objects and Swift dictionaries are **UNORDERED**.  Thou shalt not write any code that depends on the order thereof.
