### ISSUE TITLE
cocoapods?

### ISSUE THREAD

**Issue by spsammy-symbio** [dankogai/swift-json#29]
Hi,

Thanks for this awesome code!  

With respect, is there a reason why it's not available through CocoaPods?  I'm new to iOS so perhaps there a technical or philosophical reason.  It would make it easier for people to get hold of updates, like the recent fix for the latest Swift version.

thanks,

Paul

**Comment by dankogai** [comment]
I am a little reluctant because the future of Swift package is still hazy.  But if you write one pull request is always welcome.

**Comment by spsammy-symbio** [comment]
ok, clear. Thanks.
